Feature/accordion component
Vizzuality/copernicus-forest pull request #10
Opened 2019-10-21 09:24 UTC by blayhem

<img width="590" alt="image" src="https://user-images.githubusercontent.com/7013170/67568007-5a2c0700-f72b-11e9-8ff9-3400b410245d.png">

Accordion component for the bioclimatic variables page.

2019-10-22 13:36 UTC, aabdaab commented
checking ☝️

2019-10-22 13:45 UTC, aabdaab requested changes
Good job! Check the comments below about the code. There are a couple of things missing from the design as well:
1) We're missing the arrow in the accordion row - check snapshot below
![image](https://user-images.githubusercontent.com/6136899/67292048-5d7c8400-f4da-11e9-8c48-02bed2d6dc8c.png)
2) The background-color of accordion should be white and grey on hover:
![image](https://user-images.githubusercontent.com/6136899/67292158-8dc42280-f4da-11e9-845f-325da9619ad8.png)

2019-10-22 13:45 UTC, aabdaab commented on src/components/accordion/styles.scss
> +    background: #E8E8E8;
put into `settings` color variables

2019-10-22 13:45 UTC, aabdaab commented on src/components/accordion/component.jsx
> +            {activeItem === item && <div className="accordion-content">{item.content}</div>}
we can make a function out of it as it's duplicated in two places, `isActive` or sth

2019-10-22 13:50 UTC, aabdaab commented
Another thing I thought about, it can be left for a different PR. We should be consistent throughout the platform and persist the opened item in the url, I added some util functions in the filters navbar PR

2019-10-25 14:34 UTC, aabdaab commented
Hey! I'm posting here the general comments from clicking around the app:
1. On the design, it's indicated on hovering the accordion row, the chart changes color to pink:
![image](https://user-images.githubusercontent.com/6136899/67576060-c3b11300-f735-11e9-92df-0db968dca5a1.png)
It might also be good to have a `cursor: pointer` when hovering over the mini chart 💹
2. We need to tweak the y axis annotation;
**Design**
![image](https://user-images.githubusercontent.com/6136899/67577356-39b67980-f738-11e9-90b7-e45fe3e6f4de.png)
**Now**
![image](https://user-images.githubusercontent.com/6136899/67577396-4cc94980-f738-11e9-91eb-c8ce0b072e11.png)
- The font is different: in the design we've got `Anonymous Pro Regular` and the size of the font is smaller
- The unit (C) should be only on the top of the y-axis 
3. The title of the accordion should be left-aligned with the chart:
**Design**
<img width="695" alt="Screenshot 2019-10-25 at 15 09 30" src="https://user-images.githubusercontent.com/6136899/67577999-79319580-f739-11e9-8793-efc8c91fb0f8.png">

**Now**
<img width="514" alt="Screenshot 2019-10-25 at 15 08 31" src="https://user-images.githubusercontent.com/6136899/67578040-8fd7ec80-f739-11e9-816f-33110ffcf8f0.png">

4. The `background-color` of the whole accordion should be white.
5. There is no arrow on the design when having an open accordion item but I think it's OK and more intuitive to have it there, so I would leave it but we can double-check with @fannycc 👍 
![image](https://user-images.githubusercontent.com/6136899/67578232-ef35fc80-f739-11e9-9c47-66a0bfb5c6b8.png)
6. We have a gap between y-axis and the area chart that is not existent in the design:
**Design**
![image](https://user-images.githubusercontent.com/6136899/67578455-6370a000-f73a-11e9-8dea-5dad232eba03.png)
**Now**
![image](https://user-images.githubusercontent.com/6136899/67578518-7edbab00-f73a-11e9-8ba6-e358490f966a.png)
7. The line chart should be a bit thicker, in the design it's 3px. Also, the "dots" indicating the domain values (years) on the line chart should be always visible. 
![image](https://user-images.githubusercontent.com/6136899/67578695-e5f95f80-f73a-11e9-96e8-bf90254cedf0.png)
8. We need to make tooltips consistent but I think it's for a different PR as in the species summary chart we would need to do it as well. I will make a PT task for that 👍 Or should we add it to the list pinned on the slack channel? Let me know, I'm happy with both.
**Design**
![image](https://user-images.githubusercontent.com/6136899/67578977-75067780-f73b-11e9-9f35-b1662c04abcb.png)

I think the idea to feed the real data to the accordion chart is for a different PR, right? It is this item from our slack list?
![image](https://user-images.githubusercontent.com/6136899/67579569-a16ec380-f73c-11e9-8c38-3ff3091e8aed.png)
Great job overall, I'm gonna check the code now :)

2019-10-25 15:04 UTC, aabdaab reviewed
I left some comment about the typography, the rest of the code looks good 💪 ✊

2019-10-25 15:04 UTC, aabdaab commented on src/components/accordion/styles.scss
> +        // height: 12px;
Let's remove the commented code

2019-10-25 15:04 UTC, aabdaab commented on src/components/accordion/styles.scss
> +        font-size: 30px;
I think we also need to update the typography:
![image](https://user-images.githubusercontent.com/6136899/67580518-62417200-f73e-11e9-906d-8e3f37e58d5f.png)
`30px` would stand for the `$h2` typography and now in the settings file it's 32: `$font-size-h2: 32px;`
We could create a `typography` stylesheet and put all our styles for typography there. In Half-Earth we used [sass's placeholder selectors](https://sass-lang.com/documentation/at-rules/extend#placeholder-selectors) and then extended them in specific component style files. For example:
```
// typography.scss
%h1 {
  font-weight: bold;
  font-family: $font-family-1;
  line-height: 80px;
  font-size: 64px;
}
```
and then in the `.accordion-title`:
```
// accordion/styles.scss
...
.accordion-title {
   @extend %h1;
   ... some other things needed for that class ...
}
```

What do you think of that approach?

2019-10-30 14:57 UTC, kfilip94 commented
:eyes: checking

2019-10-30 17:46 UTC, kfilip94 commented
@blayhem Thank you for your changes :+1:  I'll take another look tomorrow at your PR but I found a few things that should be done:

- Following Marta's comments above:
  - `"The background-color of accordion should be white and grey on hover:"`

![67292158-8dc42280-f4da-11e9-845f-325da9619ad8](https://user-images.githubusercontent.com/15097138/67873578-9399b380-fb2b-11e9-8434-1305d88700cb.png)
  - `"We have a gap between y-axis and the area chart that is not existent in the design:"`
![image](https://user-images.githubusercontent.com/15097138/67882548-54269380-fb3a-11e9-9e2c-fdef8bcaacfd.png) You need to check Recharts documentation, but I'm not sure if this can be easily done :/

   - `"Another thing I thought about, it can be left for a different PR. We should be consistent throughout the platform and persist the opened item in the url, I added some util functions in the filters navbar PR"` - it'll be done in a new PR?

- Something went wrong here, check x-axis ;)
![image](https://user-images.githubusercontent.com/15097138/67883827-acf72b80-fb3c-11e9-9d23-f96c862f3022.png)


- The y-axis label doesn't match the design:

![image](https://user-images.githubusercontent.com/15097138/67877675-e9715a00-fb31-11e9-8b5f-441a1d7d0f53.png)
![image](https://user-images.githubusercontent.com/15097138/67877640-d9597a80-fb31-11e9-88f9-63cf84a066f3.png)
One solution could be adding the ` <Label />` inside the `<YAxis> ... <Label /> ... </YAxis>`, check documentation [here](http://recharts.org/en-US/api/Label).
![image](https://user-images.githubusercontent.com/15097138/67882109-9d2a1800-fb39-11e9-83ff-ad1214504225.png)

After adding this to the `chart/component.jsx`:
![image](https://user-images.githubusercontent.com/15097138/67881408-5daefc00-fb38-11e9-8c28-c4bf3744cad3.png)

Please notice that I added `tickSize={0}` to the `<YAxis>` component - it removes this ugly thicker line next to each tick on the y-axis.

Rember about tweaking `CustomTick` component  and adding `fill="#222222"` and `dx={-16}` to the `<text/>` - it allows to have bigger padding between a tick and the chart:
![image](https://user-images.githubusercontent.com/15097138/67882188-c054c780-fb39-11e9-973f-f7522caf5ee1.png)

And the most important, please double check it with the line chart on the `Species summary` page, because these changes can mess up a little with the styles of the species chart. So the best approach would be to include these changes in the config objects that you already use.

2019-10-31 12:23 UTC, merged